language: node_js
node_js:
    - '6.1'
    - '4.4'
matrix:
    allow_failures:
        - node_js: '0.11'
before_install:
    - npm install -g babel
    - cd react-swing
install:
    - npm install
    - npm run build
notifications:
    email: false