language: node_js
node_js:
    - '6.1'
    - '4.4'
matrix:
    allow_failures:
        - node_js: '0.11'
before_install:
    - npm install -g babel
    - cd /home/travis/build/ssanjun/react-swing
install:
    - npm install
    - babel /home/travis/build/ssanjun/react-swing/src/Swing.js --out-file /home/travis/build/ssanjun/react-swing/dist/Swing.js
notifications:
    email: false